/*
 * This file is generated by jOOQ.
 */
package fr.mazerty.torii.dao.jooq;


import fr.mazerty.torii.dao.jooq.tables.TUser;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in torii
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>torii.t_user</code>.
     */
    public static final TUser T_USER = fr.mazerty.torii.dao.jooq.tables.TUser.T_USER;
}
