/*
 * This file is generated by jOOQ.
 */
package org.zebr0.demovaadin8.dao.jooq;


import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.zebr0.demovaadin8.dao.jooq.tables.TUser;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Demovaadin8 extends SchemaImpl {

    private static final long serialVersionUID = -159350094;

    /**
     * The reference instance of <code>demovaadin8</code>
     */
    public static final Demovaadin8 DEMOVAADIN8 = new Demovaadin8();

    /**
     * The table <code>demovaadin8.t_user</code>.
     */
    public final TUser T_USER = org.zebr0.demovaadin8.dao.jooq.tables.TUser.T_USER;

    /**
     * No further instances allowed
     */
    private Demovaadin8() {
        super("demovaadin8", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.T_USER_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TUser.T_USER);
    }
}
