/*
 * This file is generated by jOOQ.
 */
package org.zebr0.demovaadin8.dao.jooq;


import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;
import org.zebr0.demovaadin8.dao.jooq.tables.TUser;


/**
 * A class modelling indexes of tables of the <code>demovaadin8</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index T_USER_PKEY = Indexes0.T_USER_PKEY;
    public static final Index T_USER_USERNAME_KEY = Indexes0.T_USER_USERNAME_KEY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index T_USER_PKEY = Internal.createIndex("t_user_pkey", TUser.T_USER, new OrderField[] { TUser.T_USER.ID }, true);
        public static Index T_USER_USERNAME_KEY = Internal.createIndex("t_user_username_key", TUser.T_USER, new OrderField[] { TUser.T_USER.USERNAME }, true);
    }
}
