/*
 * This file is generated by jOOQ.
 */
package org.zebr0.demovaadin8.dao.jooq;


import javax.annotation.Generated;

import org.zebr0.demovaadin8.dao.jooq.tables.TUser;


/**
 * Convenience access to all tables in demovaadin8
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>demovaadin8.t_user</code>.
     */
    public static final TUser T_USER = org.zebr0.demovaadin8.dao.jooq.tables.TUser.T_USER;
}
